swagger: "2.0"
info:
  description: EVC backend API
  version: "1.0.0"
  title: "EVC API"
basePath: "/api/v1"
schemes:
  - http
  - https
definitions:
  PingResponse:
    type: "object"
paths:
  /contact:
    post:
      operationId: saveContact
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /file/download/task/{taskId}/file/{fileId}:
    get:
      operationId: downloadFile
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: taskId
          in: path
          type: string
          format: uuid
          required: true
        - name: fileId
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /file/search:
    post:
      operationId: searchFileList
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /file/{id}:
    get:
      operationId: getFile
      # security:
      #   - authLoggedInUser: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /file:
    post:
      operationId: uploadFile
      responses:
        200:
          description: OK
  /auth/login:
    post:
      operationId: login
      # security:
      # - authAnyRole: []
      #   - business: []
      #   - individual: []
      #   - admin: []
      responses:
        200:
          description: OK
  /auth/logout:
    post:
      operationId: logout
      # security:
      #   - authAnyRole: []
      # security:
      #   - business: []
      #   - individual: []
      #   - admin: []
      responses:
        200:
          description: OK
  /auth/forgot_password:
    post:
      operationId: forgotPassword
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/impersonate:
    post:
      operationId: impersonate
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/invite:
    post:
      operationId: inviteUser
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/reset_password:
    post:
      operationId: resetPassword
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/r/{token}:
    get:
      operationId: retrievePassword
      # security:
      #   - authAnyRole: []
      parameters:
        - name: token
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /auth/signup:
    post:
      operationId: signup
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /auth/user:
    get:
      operationId: getAuthUser
      responses:
        200:
          description: OK
  /auth/sso/google:
    post:
      operationId: ssoGoogle
      # security:
      #   - authAnyRole: []
      responses:
        200:
          description: OK
  /user/search:
    post:
      operationId: searchUsers
      # security:
      #   - authAdminOrAgent: []
      responses:
        200:
          description: OK
  /user/:id:
    delete:
      operationId: deleteUser
      # security:
      #   - authAdminOrAgent: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /user/:id/profile:
    post:
      operationId: saveProfile
      # security:
      #   - authClient: []
      responses:
        200:
          description: OK
  /user/:id/account:
    get:
      operationId: getAccount
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /user/:id/subscription:
    get:
      operationId: listUserSubscriptionHistory
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /user/:id/balance:
    post:
      operationId: adjustBalance
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /user/:id/referral_policy:
    get:
      operationId: getReferralUserPolicy
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: saveReferralUserPolicy
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /user/:id/set_password:
    post:
      operationId: setUserPassword
      # security:
      #   - authAdminOrAgent: []
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /user/change_password:
    post:
      operationId: changePassword
      # security:
      #   - authLoggedInUser: []
      responses:
        200:
          description: OK
  /stats:
    get:
      operationId: getAdminStats
      responses:
        200:
          description: OK
  /blog/:
    get:
      operationId: listBlog
      responses:
        200:
          description: OK
    post:
      operationId: saveBlog
      responses:
        200:
          description: OK
  /blog/:id:
    get:
      operationId: getBlog
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deleteBlog
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/search:
    post:
      operationId: searchStockList
      responses:
        200:
          description: OK
  /stock/search/{symbol}:
    post:
      operationId: searchSingleStock
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/list:
    get:
      operationId: listStock
      parameters:
        - name: symbol
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/hot:
    get:
      operationId: listHotStock
      responses:
        200:
          description: OK
  /stock/watchlist:
    get:
      operationId: getWatchList
      responses:
        200:
          description: OK
  /stock/s/{symbol}:
    get:
      operationId: getStock
      parameters:
        - name: symbol
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
    delete:
      operationId: deleteStock
      parameters:
        - name: symbol
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/history:
    get:
      operationId: getStockHistory
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/watch:
    post:
      operationId: watchStock
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/unwatch:
    post:
      operationId: unwatchStock
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/inc:
    get:
      operationId: incrementStock
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/support/short:
    get:
      operationId: listStockSupportShort
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: saveStockSupportShort
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/support/long:
    get:
      operationId: listStockSupportLong
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: saveStockSupportLong
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/resistance/short:
    get:
      operationId: listStockResistanceShort
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: saveStockResistanceShort
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/resistance/long:
    get:
      operationId: listStockResistanceLong
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: saveStockResistanceLong
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/eps:
    get:
      operationId: listStockEps
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: saveStockEps
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/pe:
    get:
      operationId: listStockPe
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: saveStockPe
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/value:
    get:
      operationId: getStockFairValue
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: saveStockFairValue
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/s/{symbol}/publish:
    get:
      operationId: listStockPublish
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
    post:
      operationId: saveStockPublish
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock/support/short/{id}:
    delete:
      operationId: deleteStockSupportShort
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/support/long/{id}:
    delete:
      operationId: deleteStockSupportLong
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/resistance/short/{id}:
    delete:
      operationId: deleteStockResistanceShort
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/resistance/long/{id}:
    delete:
      operationId: deleteStockResistanceLong
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/pe/{id}:
    delete:
      operationId: deleteStockPe
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/eps/{id}:
    delete:
      operationId: deleteStockEps
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/value/{id}:
    delete:
      operationId: deleteStockFairValue
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /stock/{symbol}:
    post:
      operationId: updateStock
      parameters:
        - name: symbol
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /stock:
    put:
      operationId: createStock
      responses:
        200:
          description: OK
  /subscription:
    get:
      operationId: getMyCurrnetSubscription
      responses:
        200:
          description: OK
    post:
      operationId: provisionSubscription
      responses:
        200:
          description: OK
  /subscription/calc:
    post:
      operationId: calculateNewSubscriptionPayment
      responses:
        200:
          description: OK
  /subscription/history:
    get:
      operationId: listMySubscriptionHistory
      responses:
        200:
          description: OK
  /subscription/{id}/commit:
    post:
      operationId: commitSubscription
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /subscription/payment/{id}/card/confirm:
    post:
      operationId: confirmStripeCardPayment
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /subscription/{id}/cancel:
    post:
      operationId: cancelSubscription
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
      responses:
        200:
          description: OK
  /event:
    get:
      operationId: subscribeEvent
      responses:
        200:
          description: OK
    post:
      operationId: publishEvent
      responses:
        200:
          description: OK
  /debug:
    get:
      operationId: getDebugInfo
      responses:
        200:
          description: OK
  /account:
    get:
      operationId: getMyAccount
      responses:
        200:
          description: OK
  /stocktag:
    get:
      operationId: listStockTags
      responses:
        200:
          description: OK
    post:
      operationId: saveStockTag
      responses:
        200:
          description: OK
  /stocktag/{id}:
    delete:
      operationId: deleteStockTag
      parameters:
        - name: id
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /referral_policy/global:
    get:
      operationId: listReferralGlobalPolicy
      responses:
        200:
          description: OK
    post:
      operationId: saveReferralGlobalPolicy
      responses:
        200:
          description: OK
  /referral_policy/global/{id}:
    get:
      operationId: getReferralGlobalPolicy
      parameters:
        - name: id
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /referral_policy/{id}/enable:
    post:
      operationId: enableReferralGlobalPolicy
      parameters:
        - name: id
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
  /webhook/stripe:
    post:
      operationId: webhookStripe
      parameters:
        - name: id
          in: path
          type: string
          required: true

      responses:
        200:
          description: OK
  /checkout/stripe/session:
    get:
      operationId: fetchCheckoutSession
      responses:
        200:
          description: OK
